export const CV_DATA_SEARCH_LOAD_FAILURE = 'CV_DATA_SEARCH_LOAD_FAILURE';
export const CV_DATA_SEARCH_IS_LOADING = 'CV_DATA_SEARCH_IS_LOADING';
export const CV_DATA_SEARCH_LOAD_SUCCESS = 'CV_DATA_SEARCH_LOAD_SUCCESS';